/**
 * Movies Types
 */
const MOVIES_SAGA = 'MOVIES_SAGA'
const MOVIES_START = 'MOVIES_START'
const MOVIES_SUCCESS = 'MOVIES_SUCCESS'
const MOVIES_FAILURE = 'MOVIES_FAILURE'

/**
 * Movie Id Types
 */
const SET_MOVIE_ID = 'SET_MOVIE_ID'
const MOVIE_INFO_SAGA = 'MOVIE_INFO_SAGA'
const MOVIE_INFO_START = 'MOVIE_INFO_START'
const MOVIE_INFO_SUCCESS = 'MOVIE_INFO_SUCCESS'
const MOVIE_INFO_FAILURE = 'MOVIE_INFO_FAILURE'

/**
 * Similar Movies Types
 */
const MOVIES_SIMILAR_SAGA = 'MOVIES_SIMILAR_SAGA'
const MOVIES_SIMILAR_START = 'MOVIES_SIMILAR_START'
const MOVIES_SIMILAR_SUCCESS = 'MOVIES_SIMILAR_SUCCESS'
const MOVIES_SIMILAR_FAILURE = 'MOVIES_SIMILAR_FAILURE'

export const MovieTypes = {
  saga: MOVIES_SAGA,
  start: MOVIES_START,
  success: MOVIES_SUCCESS,
  failure: MOVIES_FAILURE,

  setId: SET_MOVIE_ID,
  sagaInfo: MOVIE_INFO_SAGA,
  startInfo: MOVIE_INFO_START,
  successInfo: MOVIE_INFO_SUCCESS,
  failureInfo: MOVIE_INFO_FAILURE,

  sagaSimilar: MOVIES_SIMILAR_SAGA,
  startSimilar: MOVIES_SIMILAR_START,
  successSimilar: MOVIES_SIMILAR_SUCCESS,
  failureSimilar: MOVIES_SIMILAR_FAILURE
}
