const MOVIES_SAGA = 'MOVIES_SAGA'
const MOVIES_START = 'MOVIES_START'
const MOVIES_SUCCESS = 'MOVIES_SUCCESS'
const MOVIES_FAILURE = 'MOVIES_FAILURE'

const SET_MOVIE_ID = 'SET_MOVIE_ID'
const MOVIE_INFO_SAGA = 'MOVIE_INFO_SAGA'
const MOVIE_INFO_START = 'MOVIE_INFO_START'
const MOVIE_INFO_SUCCESS = 'MOVIE_INFO_SUCCESS'
const MOVIE_INFO_FAILURE = 'MOVIE_INFO_FAILURE'

export const MovieTypes = {
  saga: MOVIES_SAGA,
  start: MOVIES_START,
  success: MOVIES_SUCCESS,
  failure: MOVIES_FAILURE,

  setId: SET_MOVIE_ID,
  sagaInfo: MOVIE_INFO_SAGA,
  startInfo: MOVIE_INFO_START,
  successInfo: MOVIE_INFO_SUCCESS,
  failureInfo: MOVIE_INFO_FAILURE
}
